version: "3"

tasks:
  dev:
    cmds:
      - odin run ./test -debug

  test:
    cmds:
      - cmd: odin test ./test -debug
        platforms: [windows]
      - cmd: odin build ./test -build-mode:test -debug -define:ODIN_TEST_THREADS=1 && sudo setcap cap_sys_admin+ep test.bin && ./test.bin
        platforms: [linux]

