version: "3"

tasks:
  dev:
    cmds:
      - odin run . -debug -- {{.CLI_ARGS}}
  build:demo:
    cmds:
      - odin build .

  test:
    cmds:
      - cmd: odin test .
  test:debug:
    cmds:
      - cmd: odin test . -debug

